version: '3'

services:
  consul:
    hostname: consul
    restart: always
    container_name: consul
    image: hashicorp/consul:1.16
    # build:
    #   context: ./consul
    #   dockerfile: Dockerfile
    environment:
      DISABLE_DEFAULT_SERVER: 1
    privileged: true
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "8520:8520"
    networks:
      - default
      - service_network
    volumes:
      - ./consul/data:/consul/data
      - ./consul/log:/consul/log
    #command: kv import -http-addr=127.0.0.1:8500 @consul/data/consul-kv.json

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    #extra_hosts:
    #  - "kafka-server.dev:127.0.0.1"
  kafka:
    image: wurstmeister/kafka
    #hostname: kafka
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    extra_hosts:
      - "kafka-server.dev:192.168.201.138"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_ADVERTISED_HOST_NAME=kafka-server.dev
      #- KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server.dev:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      #- KAFKA_CREATE_TOPICS=test:1:1
    depends_on:
      - zookeeper
    networks:
      - default
      - service_network
  kafka-manager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    restart: always
    container_name: kafka-manager
    ports:
      - "19092:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181

networks:
  service_network:
    driver: bridge
    name: service-network
    external: true
    